# Generated by Django 3.2.6 on 2021-08-27 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rd', models.CharField(max_length=50)),
                ('tec', models.CharField(max_length=100)),
                ('eventum', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.CharField(max_length=200)),
                ('numline', models.IntegerField()),
                ('status', models.CharField(choices=[('Libre', 'Libre'), ('Ocupado', 'Ocupado'), ('Duplicado', 'Duplicado')], default='Libre', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
