# Generated by Django 3.2.7 on 2021-09-28 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route_ds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeds',
            name='client',
        ),
        migrations.RemoveField(
            model_name='routeds',
            name='eventum',
        ),
        migrations.RemoveField(
            model_name='routeds',
            name='numline',
        ),
        migrations.RemoveField(
            model_name='routeds',
            name='tec',
        ),
        migrations.AlterField(
            model_name='routeds',
            name='rd',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route_ds.routeds')),
            ],
        ),
        migrations.CreateModel(
            name='NumLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('numline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route_ds.routeds')),
            ],
        ),
        migrations.CreateModel(
            name='Eventum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeventum', models.IntegerField()),
                ('eventum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route_ds.routeds')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route_ds.routeds')),
            ],
        ),
    ]
