# Generated by Django 3.2.7 on 2021-09-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route_ds', '0002_auto_20210928_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('tec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route_ds.routeds')),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nombre',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Tecnico',
        ),
    ]
