# Generated by Django 3.1.13 on 2021-09-29 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Eventum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NumLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numline', models.IntegerField()),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='routeds.client')),
            ],
        ),
        migrations.CreateModel(
            name='Tec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RouteDistinguiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rd', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Libre', 'Libre'), ('Ocupado', 'Ocupado'), ('Duplicado', 'Duplicado')], default='Libre', max_length=10)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='routeds.client')),
                ('eventum', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='routeds.eventum')),
                ('numline', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='routeds.numline')),
                ('tec', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='routeds.tec')),
            ],
        ),
    ]
